### ISSUE TITLE
Class PendingUserEmail not allowing mass assignment

### ISSUE THREAD

**Issue by jsilva74** [pascalbaljetmedia/laravel-verify-new-email#1]
Hi.

I'm getting this error when calling newEmail method with Laravel 6.9 under Valet on MacOS:
`Add [user_type] to fillable property to allow mass assignment on [ProtoneMedia\LaravelVerifyNewEmail\PendingUserEmail].`

Checking the PendingUserEmail class, it's doesn't have the fillable attribute indeed.

Thanks for this package and any help you could provide.

**Comment by pascalbaljet** [comment]
I just tagged v1.0.2 with a fix. I usually unguard all my models so I didn't catch this during development. Thanks for noticing!
