### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by hamzaelmaghari** [pascalbaljetmedia/laravel-verify-new-email#11]
Please,
This package is great, If you could make it compatible with Laravel 9.
Coming soon...

**Comment by pascalbaljet** [comment]
Fixed in v1.5.0: https://github.com/protonemedia/laravel-verify-new-email/releases/tag/v1.5.0

**Comment by hamzaelmaghari** [comment]
> Fixed in v1.5.0: https://github.com/protonemedia/laravel-verify-new-email/releases/tag/v1.5.0

# Great to see this heppening
