### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::forUser()

### ISSUE THREAD

**Issue by apexdivision** [pascalbaljetmedia/laravel-verify-new-email#3]
Hello,

When I am using newEmail method in update profile section, like:
$user->newEmail(request('email'));
I am getting the error as below:

Call to undefined method Illuminate\Foundation\Application::forUser()

App\User::clearPendingEmail
vendor/protonemedia/laravel-verify-new-email/src/MustVerifyNewEmail.php:65
Which is:
app(config('verify-new-email.model'))->forUser($this)->get()->each->delete();

Please advise. I am using Laravel 7.12

Thank you

**Comment by pascalbaljet** [comment]
How did you configure `verify-new-email.model`? By default it is `\ProtoneMedia\LaravelVerifyNewEmail\PendingUserEmail::class`, did you update it manually?

**Comment by apexdivision** [comment]
No, I am using default installation and only for changed emails, followed exact steps and verify-new-email.model is \ProtoneMedia\LaravelVerifyNewEmail\PendingUserEmail::class
`'model' => \ProtoneMedia\LaravelVerifyNewEmail\PendingUserEmail::class,`

**Comment by deanthvr** [comment]
I am having the same issue.  Installed on Laravel 7.4.  When calling the newEmail() method, I receive the same message:  "Call to undefined method Illuminate\Foundation\Application::forUser()."   Is there a fix for this?

**Comment by pascalbaljet** [comment]
I've tagged a new version which is more explicit about the error:
https://github.com/protonemedia/laravel-verify-new-email/releases/tag/v1.2.1
