### ISSUE TITLE
Email not getting verified

### ISSUE THREAD

**Issue by maxillarious** [pascalbaljetmedia/laravel-verify-new-email#4]
Hi,  i did every thing just as the instruction implies but i think am missing something here.

When ever i initialise this `$user->newEmail($data['email']);` the email address specified receives the new email verification link but when i click on the link,

i get this Google Chrome **This site can’t be reached** page instead of verifying and redirecting to homepage.

Meanwhile the old email address doesn't change to the new one and the pending email is still there.

Thank you.

**Comment by maxillarious** [comment]
Haa, Found my problem.

I forgot that i was not using xampp.
i had to change `localhost` to `http://127.0.0.1:8000/`, on the link in chrome but now am getting a 403 | Invalid signature error.

Does it mean i should still change `localhost` to `http://127.0.0.1:8000/` in it's file, if true how can i find where it is located.

**Comment by maxillarious** [comment]
Wow, wasn't easy but finally fixed it but i won't call it a problem but blindness(because i couldn't see it).

SOLUTION:
In command prompt(cmd) stop server by pressing `Ctrl` + `c`.

THEN:

In `.env` file,

changed the app url from `http://localhost` to `http://127.0.0.1:8000`, 

THEN:

In cmd i executed this `php artisan config:clear`

THEN:

In cmd i executed this `php artisan serve` to start server

Here is a link for reference [Starkoverflow](https://stackoverflow.com/a/44880497/12115039)

**Comment by pascalbaljet** [comment]
Glad you fixed it!
